version: "3"
services:
  mysql:
    container_name: team-mirai-mysql # コンテナ名は適宜置き換えること
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password --port 13306
    tty: true
    stdin_open: false
    env_file:
      - .env.local # 環境変数ファイルのパスを指定. .env.local内でMYSQL_DATABASEを定義していた場合、自動的にDBが作成される
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    expose:
      - "13306"
    networks:
      - app-net
    ports:
      - "13306:13306"

networks:
  app-net:
    driver: bridge
